#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Mar 13 21:16:35 CET 2019
# SW Build 2405991 on Thu Dec  6 23:36:41 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim Controller_TB_func_synth -key {Post-Synthesis:sim_1:Functional:Controller_TB} -tclbatch Controller_TB.tcl -view /home/daniel/SPI_project/Controller_TB_behav.wcfg -view /home/daniel/SPI_project/Controller_TB_behav1.wcfg -log simulate.log
