set_property SRC_FILE_INFO {cfile:/home/daniel/Desktop/FPGAx/FPGA/assets/projects/Controller_v2/Project.srcs/constrs_1/new/BASYS_3.xdc rfile:../../../Project.srcs/constrs_1/new/BASYS_3.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W5 IOSTANDARD LVCMOS33 } [get_ports clk]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U16    IOSTANDARD LVCMOS33 } [get_ports { led[0] }]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E19    IOSTANDARD LVCMOS33 } [get_ports { led[1] }]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U19    IOSTANDARD LVCMOS33 } [get_ports { led[2] }]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V19    IOSTANDARD LVCMOS33 } [get_ports { led[3] }]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W18    IOSTANDARD LVCMOS33 } [get_ports { led[4] }]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U15    IOSTANDARD LVCMOS33 } [get_ports { led[5] }]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U14    IOSTANDARD LVCMOS33 } [get_ports { led[6] }]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V14    IOSTANDARD LVCMOS33 } [get_ports { led[7] }]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V13    IOSTANDARD LVCMOS33 } [get_ports { led[8] }]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V3     IOSTANDARD LVCMOS33 } [get_ports { led[9] }]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W3     IOSTANDARD LVCMOS33 } [get_ports { led[10] }]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U3     IOSTANDARD LVCMOS33 } [get_ports { led[11] }]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P3     IOSTANDARD LVCMOS33 } [get_ports { led[12] }]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN N3     IOSTANDARD LVCMOS33 } [get_ports { led[13] }]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P1     IOSTANDARD LVCMOS33 } [get_ports { led[14] }]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L1     IOSTANDARD LVCMOS33 } [get_ports { led[15] }]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J1     IOSTANDARD LVCMOS33 } [get_ports encA_1];	#Sch name = JA1
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L2     IOSTANDARD LVCMOS33 } [get_ports encB_1];	#Sch name = JA2
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K17     IOSTANDARD LVCMOS33 } [get_ports ss];	#Sch name = JC1
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M18     IOSTANDARD LVCMOS33 } [get_ports sck];	#Sch name = JC2
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN N17     IOSTANDARD LVCMOS33 } [get_ports miso];	#Sch name = JC3
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P18     IOSTANDARD LVCMOS33 } [get_ports mosi];	#Sch name = JC4
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J3     IOSTANDARD LVCMOS33 } [get_ports encA_2]; #Sch name = XA1_P & Vauxp6
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L3     IOSTANDARD LVCMOS33 } [get_ports encB_2]; #Sch name = XA2_P & Vauxp14
